"""
tests/test_pg_backend.py
========================
Prompt cuối §65: PostgreSQL là nguồn sự thật khi đặt DATABASE_URL.

  - lớp tương thích (pg_compat) dịch đúng SQL kiểu SQLite của ứng dụng sang PostgreSQL;
  - sao lưu khi chạy PostgreSQL: chụp schema ra file SQLite (bản chụp nhất quán, đối chiếu
    checksum) rồi khôi phục ngược bằng `migrate` -> dữ liệu y hệt (khứ hồi không mất gì).
Phần cần PostgreSQL thật dùng `pgserver` (gói dev); không có thì bỏ qua.
"""
from __future__ import annotations

import sqlite3

import pytest


def test_translate_maps_sqlite_dialect():
    from mateai.infrastructure.database.pg_compat import translate
    q = translate("SELECT * FROM [tasks] WHERE title LIKE ? AND d > datetime('now','-7 days') -- 50%", True)
    assert '"tasks"' in q and "ILIKE %s" in q and "interval '-7 days'" in q
    assert "50%" not in q and "--" not in q            # chú thích bị bỏ, không thành tham số giả
    ddl = translate("CREATE TABLE IF NOT EXISTS x (id INTEGER PRIMARY KEY AUTOINCREMENT, "
                    "timestamp TEXT DEFAULT CURRENT_TIMESTAMP, n REAL, b BLOB)", False)
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
    assert "timestamp TEXT DEFAULT to_char(now()" in ddl   # tên cột `timestamp` giữ nguyên, chỉ đổi kiểu
    assert "n DOUBLE PRECISION" in ddl and "b BYTEA" in ddl


def test_type_map_single_source():
    from mateai.infrastructure.database import pg_migration
    from mateai.infrastructure.database.pg_compat import sqlite_type_to_pg
    for decl in ("INTEGER", "VARCHAR(20)", "REAL", "BLOB", "", "DATETIME", "NUMERIC", "BOOLEAN"):
        assert pg_migration._pg_type(decl) == sqlite_type_to_pg(decl)
    assert sqlite_type_to_pg("BOOLEAN") == "BIGINT" and sqlite_type_to_pg("DATETIME") == "TEXT"


pgserver = pytest.importorskip("pgserver", reason="cần gói dev pgserver (PostgreSQL thật) — requirements-dev.txt")


@pytest.fixture(scope="module")
def pg_dsn(tmp_path_factory):
    srv = pgserver.get_server(str(tmp_path_factory.mktemp("pgb")), cleanup_mode="stop")
    yield srv.get_uri()
    try:
        srv.cleanup()
    except Exception:
        pass


def _source(path):
    con = sqlite3.connect(str(path))
    con.executescript("""
        CREATE TABLE departments (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL,
                                  created_at TEXT DEFAULT CURRENT_TIMESTAMP);
        CREATE TABLE employees (id INTEGER PRIMARY KEY AUTOINCREMENT, dept_id INTEGER, name TEXT,
                                salary REAL, avatar BLOB, status TEXT DEFAULT 'active',
                                FOREIGN KEY (dept_id) REFERENCES departments (id) ON DELETE CASCADE);
        CREATE INDEX idx_emp_dept ON employees (dept_id);
        CREATE TABLE audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, action_type TEXT, payload TEXT);
    """)
    con.execute("INSERT INTO departments (name) VALUES ('Kế toán')")
    con.executemany("INSERT INTO employees (dept_id, name, salary, avatar) VALUES (1, ?, ?, ?)",
                    [("Nguyễn Văn Á", 12500000.5, b"\x00\x01\xff"), ("Trần Thị B", None, None)])
    con.execute("INSERT INTO audit_logs (action_type, payload) VALUES ('t', '{\"tiền\": 1}')")
    con.commit()
    con.close()


def test_backup_roundtrip_postgres_to_sqlite_and_back(tmp_path, pg_dsn):
    import psycopg
    from mateai.infrastructure.database import pg_migration as pm
    src = tmp_path / "src.db"
    _source(src)
    assert pm.migrate(src, pg_dsn, schema="bk_live")["ok"]
    with psycopg.connect(pg_dsn, autocommit=True) as conn:       # dữ liệu mới chỉ có bên PostgreSQL
        conn.execute("INSERT INTO bk_live.employees (dept_id, name, salary) VALUES (1, 'Lê Văn C', 9.25)")

    snap = tmp_path / "snap.db"
    rep = pm.export_to_sqlite(pg_dsn, "bk_live", snap)
    rows = {t["table"]: t["rows"] for t in rep["tables"]}
    assert rows == {"audit_logs": 1, "departments": 1, "employees": 3}
    with pytest.raises(pm.MigrationError, match="không ghi đè"):
        pm.export_to_sqlite(pg_dsn, "bk_live", snap)

    # Khôi phục bản chụp vào schema khác -> y hệt nguồn PostgreSQL (checksum từng bảng).
    back = pm.migrate(snap, pg_dsn, schema="bk_restored")
    assert back["ok"] and not back["foreign_keys_not_validated"]
    live = {t["table"]: t["checksum"] for t in rep["tables"]}
    assert {t["table"]: t["checksum_pg"] for t in back["tables"]} == live
    with psycopg.connect(pg_dsn, autocommit=True) as conn:
        # tự tăng tiếp tục sau id lớn nhất; mặc định cột + khoá ngoại CASCADE còn nguyên
        conn.execute("INSERT INTO bk_restored.employees (dept_id, name) VALUES (1, 'Mới')")
        new = conn.execute("SELECT id, status FROM bk_restored.employees WHERE name = 'Mới'").fetchone()
        assert new == (4, "active")
        conn.execute("DELETE FROM bk_restored.departments WHERE id = 1")
        assert conn.execute("SELECT count(*) FROM bk_restored.employees").fetchone()[0] == 0
        assert conn.execute("SELECT count(*) FROM pg_indexes WHERE schemaname = 'bk_restored' "
                            "AND indexname = 'idx_emp_dept'").fetchone()[0] == 1
        with pytest.raises(psycopg.errors.RaiseException, match="append-only"):
            conn.execute("DELETE FROM bk_restored.audit_logs")
    pm.rollback(pg_dsn, "bk_live")
    pm.rollback(pg_dsn, "bk_restored")
