# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Dương Thanh Lịch — VN-MateAI. See LICENSE and NOTICE.
"""
mateai/infrastructure/database/pg_compat.py
===========================================
Chạy tầng persistence (viết cho SQLite) trên PostgreSQL — prompt cuối §65 (cutover).

`open_sqlite()` (erp_database) là điểm mở kết nối DUY NHẤT; khi có `DATABASE_URL`
(postgresql://…) nó trả `PgConnection` ở đây — cùng giao diện mà code đang dùng:
`execute / cursor / executemany / executescript / fetch* / lastrowid / rowcount / with`,
dòng kết quả vừa đánh chỉ số vừa đọc theo tên (như `sqlite3.Row`).

Dịch SQL (chỉ những gì repo dùng — kiểm bằng toàn bộ bộ test chạy trên PostgreSQL):
  `?` -> `%s`, `%` -> `%%` · `LIKE` -> `ILIKE` (SQLite không phân biệt hoa thường với ASCII)
  `INSERT OR IGNORE` -> `ON CONFLICT DO NOTHING` · `INSERT OR REPLACE` -> `ON CONFLICT (pk) DO UPDATE`
  `datetime('now', '-N days')` -> `to_char(now() - interval …)`
  DDL: `INTEGER PRIMARY KEY [AUTOINCREMENT]` -> identity; kiểu theo `sqlite_type_to_pg` (dùng chung
  với công cụ di trú); `DEFAULT CURRENT_TIMESTAMP` -> chuỗi cùng định dạng SQLite
  `PRAGMA table_info` -> information_schema · PRAGMA khác -> bỏ qua
  INSERT vào bảng có cột identity -> thêm `RETURNING` để `lastrowid` đúng như SQLite.
Kiểu: bool -> 0/1, datetime -> chuỗi như sqlite3, Decimal trả về -> int / float.
"""
from __future__ import annotations

import datetime as _dt
import decimal
import logging
import re
import sqlite3
import threading
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

logger = logging.getLogger(__name__)


# ── Kiểu dữ liệu (một nguồn cho DDL lúc chạy + pg_migration) ─────────────────

def sqlite_type_to_pg(declared: str) -> str:
    """Theo quy tắc type affinity của SQLite."""
    t = (declared or "").upper()
    if "INT" in t or "BOOL" in t:
        return "BIGINT"
    if any(k in t for k in ("CHAR", "CLOB", "TEXT", "DATE", "TIME")):
        return "TEXT"
    if "BLOB" in t:
        return "BYTEA"
    if any(k in t for k in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if any(k in t for k in ("NUMERIC", "DECIMAL")):
        return "NUMERIC"
    return "TEXT"


NOW_TEXT = "to_char(now(), 'YYYY-MM-DD HH24:MI:SS')"


# ── Dịch SQL ─────────────────────────────────────────────────────────────────

def _outside_quotes(sql: str):
    """Chia câu SQL thành (đoạn, có_trong_ngoặc) để không đụng vào chuỗi ký tự.
    Comment `-- …` (ngoài ngoặc) bị bỏ hẳn — kể cả khi trong comment có dấu nháy."""
    out, buf, i, n = [], [], 0, len(sql)
    while i < n:
        ch = sql[i]
        if ch in ("'", '"'):
            if buf:
                out.append(("".join(buf), False))
                buf = []
            j = i + 1
            while j < n:
                if sql[j] == ch:
                    if j + 1 < n and sql[j + 1] == ch:      # '' hoặc "" bên trong
                        j += 2
                        continue
                    break
                j += 1
            out.append((sql[i:j + 1], True))
            i = j + 1
            continue
        if ch == "-" and i + 1 < n and sql[i + 1] == "-":
            j = sql.find(chr(10), i)
            i = n if j < 0 else j                            # giữ ký tự xuống dòng
            continue
        buf.append(ch)
        i += 1
    if buf:
        out.append(("".join(buf), False))
    return out


_DDL_RE = re.compile(r"^\s*(CREATE\s+TABLE|ALTER\s+TABLE)", re.IGNORECASE)
_CONSTRAINT_START = re.compile(r"^\s*(PRIMARY|FOREIGN|UNIQUE|CHECK|CONSTRAINT)\b", re.IGNORECASE)
_COLDEF = re.compile(r"^(\s*\"?[A-Za-z_][A-Za-z0-9_]*\"?\s+)([A-Za-z]+(?:\s*\([^)]*\))?)(.*)$", re.DOTALL)


def _map_coldef(item: str) -> str:
    """'tên KIỂU phần_còn_lại' -> chỉ đổi KIỂU (tên cột như `timestamp`, `date` giữ nguyên)."""
    if _CONSTRAINT_START.match(item):
        return item
    m = _COLDEF.match(item)
    if not m:
        return item
    head, typ, rest = m.groups()
    if re.match(r"(?i)INTEGER\s*$", typ) and re.match(r"(?i)\s*PRIMARY\s+KEY", rest):
        rest = re.sub(r"(?i)^\s*PRIMARY\s+KEY(\s+AUTOINCREMENT)?", "", rest)
        return f"{head}BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY{rest}"
    return f"{head}{sqlite_type_to_pg(typ)}{rest}"


def _split_top(body: str) -> List[str]:
    parts, depth, cur, quoted = [], 0, [], None
    for ch in body:
        if quoted:
            cur.append(ch)
            if ch == quoted:
                quoted = None
            continue
        if ch in ("'", '"'):
            quoted = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        elif ch == "," and depth == 0:
            parts.append("".join(cur))
            cur = []
            continue
        cur.append(ch)
    parts.append("".join(cur))
    return parts


def _ddl(sql: str) -> str:
    s = re.sub(r"DEFAULT\s+CURRENT_TIMESTAMP", f"DEFAULT {NOW_TEXT}", sql, flags=re.IGNORECASE)
    m = re.match(r"(?is)^(\s*ALTER\s+TABLE\s+\S+\s+ADD\s+(?:COLUMN\s+)?)(.*)$", s)
    if m:
        return m.group(1) + _map_coldef(m.group(2))
    if re.match(r"(?i)^\s*ALTER", s):
        return s
    open_i, close_i = s.find("("), s.rfind(")")
    if open_i < 0 or close_i < 0:
        return s
    items = _split_top(s[open_i + 1:close_i])
    return s[:open_i + 1] + ",".join(_map_coldef(it) for it in items) + s[close_i:]


_DATETIME_NOW = re.compile(r"datetime\('now'\s*,\s*'(-?\d+)\s+(day|days|hour|hours|minute|minutes)'\)",
                           re.IGNORECASE)


def _strip_comments(sql: str) -> str:
    return "".join(chunk for chunk, _q in _outside_quotes(sql))


def translate(sql: str, has_params: bool) -> str:
    s = _strip_comments(sql).strip().rstrip(";")
    if _DDL_RE.match(s):
        s = _ddl(s)
    s = _DATETIME_NOW.sub(lambda m: f"to_char(now() + interval '{m.group(1)} {m.group(2)}', "
                                    "'YYYY-MM-DD HH24:MI:SS')", s)
    out = []
    for chunk, quoted in _outside_quotes(s):
        if quoted:
            out.append(chunk.replace("%", "%%") if has_params else chunk)
            continue
        if has_params:
            chunk = chunk.replace("%", "%%")
        chunk = chunk.replace("?", "%s")
        chunk = re.sub(r"\[([A-Za-z_][A-Za-z0-9_]*)\]", r'"\1"', chunk)     # [bảng] -> "bảng"
        # rowid (cột ẩn SQLite, chỉ dùng làm tiêu chí xếp phụ theo thứ tự chèn) -> ctid.
        chunk = re.sub(r"\browid\b", "ctid", chunk, flags=re.IGNORECASE)
        chunk = re.sub(r"\bNOT\s+LIKE\b", "NOT ILIKE", chunk, flags=re.IGNORECASE)
        chunk = re.sub(r"(?<!NOT )\bLIKE\b", "ILIKE", chunk, flags=re.IGNORECASE)
        out.append(chunk)
    return "".join(out)


# ── Kiểu tham số / kết quả ───────────────────────────────────────────────────

def _param(v: Any) -> Any:
    if isinstance(v, bool):
        return int(v)
    if isinstance(v, _dt.datetime):
        return v.isoformat(" ")          # như bộ chuyển đổi mặc định của sqlite3
    if isinstance(v, _dt.date):
        return v.isoformat()
    return v


def _params(p: Any) -> Any:
    if p is None:
        return None
    if isinstance(p, dict):
        return {k: _param(v) for k, v in p.items()}
    return [_param(v) for v in p]


def _value(v: Any) -> Any:
    if isinstance(v, decimal.Decimal):
        return int(v) if v == v.to_integral_value() else float(v)
    if isinstance(v, memoryview):
        return bytes(v)
    return v


class PgRow(tuple):
    """Giống sqlite3.Row: row[0], row["col"], row.keys(), dict(row)."""

    def __new__(cls, values: Sequence[Any], names: Sequence[str]):
        obj = super().__new__(cls, (_value(v) for v in values))
        obj._names = list(names)
        return obj

    def keys(self) -> List[str]:
        return list(self._names)

    def __getitem__(self, key):  # type: ignore[override]
        if isinstance(key, str):
            try:
                return tuple.__getitem__(self, self._names.index(key))
            except ValueError:
                lowered = [n.lower() for n in self._names]
                return tuple.__getitem__(self, lowered.index(key.lower()))
        return tuple.__getitem__(self, key)


# ── Danh mục (cache theo schema) ─────────────────────────────────────────────

_CATALOG_LOCK = threading.Lock()
_IDENTITY: Dict[Tuple[str, str], Optional[str]] = {}
_PKEYS: Dict[Tuple[str, str], List[str]] = {}


def _identity_col(cur, schema: str, table: str) -> Optional[str]:
    key = (schema, table.lower())
    with _CATALOG_LOCK:
        if key in _IDENTITY:
            return _IDENTITY[key]
    cur.execute("SELECT column_name FROM information_schema.columns WHERE table_schema = %s AND table_name = %s "
                "AND (is_identity = 'YES' OR column_default LIKE 'nextval(%%')", (schema, table.lower()))
    row = cur.fetchone()
    with _CATALOG_LOCK:
        _IDENTITY[key] = row[0] if row else None
    return _IDENTITY[key]


def _pkey(cur, schema: str, table: str) -> List[str]:
    key = (schema, table.lower())
    with _CATALOG_LOCK:
        if key in _PKEYS:
            return _PKEYS[key]
    cur.execute("""SELECT a.attname FROM pg_index i
                   JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
                   WHERE i.indrelid = (quote_ident(%s) || '.' || quote_ident(%s))::regclass AND i.indisprimary""",
                (schema, table.lower()))
    cols = [r[0] for r in cur.fetchall()]
    with _CATALOG_LOCK:
        _PKEYS[key] = cols
    return cols


#: Khoá ngoại chưa gắn được vì bảng đích chưa có (SQLite cho phép, PostgreSQL thì không):
#: (schema) -> [(bảng, câu ALTER)] — gắn ngay khi bảng đích xuất hiện.
_PENDING_FK: Dict[str, List[Tuple[str, str]]] = {}
_FK_RE = re.compile(r",\s*FOREIGN\s+KEY\s*\(\s*(\w+)\s*\)\s*REFERENCES\s+(\w+)\s*\(\s*(\w+)\s*\)"
                    r"(\s+ON\s+DELETE\s+(?:CASCADE|SET\s+NULL|NO\s+ACTION|RESTRICT))?", re.IGNORECASE)
_CREATE_RE = re.compile(r"^\s*CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?\"?(\w+)\"?", re.IGNORECASE)


def _table_exists(cur, schema: str, table: str) -> bool:
    cur.execute("SELECT 1 FROM information_schema.tables WHERE table_schema = %s AND table_name = %s",
                (schema, table.lower()))
    return cur.fetchone() is not None


def clear_catalog_cache() -> None:
    with _CATALOG_LOCK:
        _IDENTITY.clear()
        _PKEYS.clear()
        _PENDING_FK.clear()


_INSERT_RE = re.compile(r"^\s*INSERT\s+(OR\s+(IGNORE|REPLACE)\s+)?INTO\s+\"?([A-Za-z_][A-Za-z0-9_]*)\"?\s*(\(([^)]*)\))?",
                        re.IGNORECASE | re.DOTALL)
_PRAGMA_RE = re.compile(r"^\s*PRAGMA\s+(\w+)\s*(\(\s*\"?(\w+)\"?\s*\))?\s*(=\s*\w+)?\s*;?\s*$", re.IGNORECASE)


class PgCursor:
    def __init__(self, conn: "PgConnection") -> None:
        self._conn = conn
        self._cur = conn._raw.cursor()
        self._rows: Optional[List[PgRow]] = None
        self._pos = 0
        self.lastrowid: Optional[int] = None
        self.rowcount = -1
        self.description = None

    # -- thực thi
    def execute(self, sql: str, params: Any = None) -> "PgCursor":
        self._rows, self._pos, self.lastrowid = None, 0, None
        m = _PRAGMA_RE.match(sql)
        if m:
            return self._pragma(m.group(1).lower(), m.group(3))
        if re.match(r"^\s*BEGIN(\s+(IMMEDIATE|EXCLUSIVE|DEFERRED))?\s*;?\s*$", sql, re.IGNORECASE):
            return self                    # psycopg đã ở trong transaction
        params = _params(params)
        has_params = bool(params)
        q = translate(sql, has_params)
        created = _CREATE_RE.match(q)
        if created:
            q = self._defer_missing_fks(q, created.group(1))
        ins = _INSERT_RE.match(q)
        returning = None
        if ins:
            table = ins.group(3)
            if ins.group(2):
                q = self._insert_or(q, ins, table)
            if " RETURNING " not in q.upper():
                returning = _identity_col(self._cur, self._conn.schema, table)
                if returning:
                    q = f'{q} RETURNING "{returning}"'
        self._run(q, params if has_params else None)
        self.rowcount = self._cur.rowcount
        self.description = self._cur.description
        if created:
            self._apply_pending_fks()
        if returning:
            row = self._cur.fetchone()
            self.lastrowid = int(row[0]) if row and row[0] is not None else None
            self._rows = []
        return self

    def _run(self, q: str, params: Any = None, many: bool = False) -> None:
        """Mỗi câu một savepoint: lỗi một câu không làm hỏng cả transaction (giống SQLite);
        lỗi PostgreSQL đổi sang kiểu sqlite3 mà code đang bắt."""
        import psycopg
        raw = self._conn._raw
        in_tx = raw.info.transaction_status != 0
        if in_tx:
            raw.execute("SAVEPOINT vnmate_stmt")          # cursor riêng: không đè kết quả
        try:
            if many:
                self._cur.executemany(q, params)
            else:
                self._cur.execute(q, params)
        except psycopg.Error as exc:
            if in_tx:
                raw.execute("ROLLBACK TO SAVEPOINT vnmate_stmt")
            else:
                raw.rollback()
            if isinstance(exc, psycopg.errors.IntegrityError):
                raise sqlite3.IntegrityError(str(exc)) from exc
            if isinstance(exc, (psycopg.errors.UndefinedTable, psycopg.errors.UndefinedColumn,
                                psycopg.errors.SyntaxError, psycopg.OperationalError,
                                psycopg.errors.LockNotAvailable, psycopg.errors.QueryCanceled)):
                raise sqlite3.OperationalError(str(exc)) from exc
            raise sqlite3.DatabaseError(str(exc)) from exc
        if in_tx:
            raw.execute("RELEASE SAVEPOINT vnmate_stmt")

    def _defer_missing_fks(self, q: str, table: str) -> str:
        schema = self._conn.schema
        pending = []

        def _strip(m: "re.Match[str]") -> str:
            col, ref, ref_col, on_delete = m.group(1), m.group(2), m.group(3), m.group(4) or ""
            if _table_exists(self._cur, schema, ref) or ref.lower() == table.lower():
                return m.group(0)
            pending.append((ref.lower(), f'ALTER TABLE "{table}" ADD CONSTRAINT "fk_{table}_{col}" '
                                         f'FOREIGN KEY ("{col}") REFERENCES "{ref}" ("{ref_col}"){on_delete}'))
            return ""

        q2 = _FK_RE.sub(_strip, q)
        if pending:
            with _CATALOG_LOCK:
                _PENDING_FK.setdefault(schema, []).extend(pending)
        return q2

    def _apply_pending_fks(self) -> None:
        schema = self._conn.schema
        with _CATALOG_LOCK:
            todo = list(_PENDING_FK.get(schema, []))
        for ref, alter in todo:
            if _table_exists(self._cur, schema, ref):
                try:
                    self._run(alter)
                except sqlite3.DatabaseError as exc:
                    logger.warning("[pg_compat] Không gắn được khoá ngoại hoãn: %s — %s", alter, exc)
                with _CATALOG_LOCK:
                    if (ref, alter) in _PENDING_FK.get(schema, []):
                        _PENDING_FK[schema].remove((ref, alter))

    def _insert_or(self, q: str, m: "re.Match[str]", table: str) -> str:
        q = re.sub(r"^\s*INSERT\s+OR\s+(IGNORE|REPLACE)\s+INTO", "INSERT INTO", q, flags=re.IGNORECASE)
        if m.group(2).upper() == "IGNORE":
            return q + " ON CONFLICT DO NOTHING"
        pk = _pkey(self._cur, self._conn.schema, table)
        cols = [c.strip().strip('"') for c in (m.group(5) or "").split(",") if c.strip()]
        upd = [c for c in cols if c not in pk]
        if not pk:
            return q
        tail = ", ".join(f'"{c}" = EXCLUDED."{c}"' for c in upd) if upd else None
        conflict = ", ".join(f'"{c}"' for c in pk)
        return q + (f" ON CONFLICT ({conflict}) DO UPDATE SET {tail}" if tail else f" ON CONFLICT ({conflict}) DO NOTHING")

    def _pragma(self, name: str, arg: Optional[str]) -> "PgCursor":
        if name == "table_info" and arg:
            self._cur.execute("""
                SELECT c.ordinal_position - 1, c.column_name, c.data_type,
                       CASE WHEN c.is_nullable = 'NO' THEN 1 ELSE 0 END, c.column_default,
                       CASE WHEN EXISTS (SELECT 1 FROM information_schema.table_constraints tc
                                         JOIN information_schema.key_column_usage k
                                           ON k.constraint_name = tc.constraint_name AND k.table_schema = tc.table_schema
                                         WHERE tc.table_schema = c.table_schema AND tc.table_name = c.table_name
                                           AND tc.constraint_type = 'PRIMARY KEY' AND k.column_name = c.column_name)
                            THEN 1 ELSE 0 END
                FROM information_schema.columns c
                WHERE c.table_schema = %s AND c.table_name = %s ORDER BY c.ordinal_position""",
                (self._conn.schema, arg.lower()))
            self._rows = [PgRow(r, ["cid", "name", "type", "notnull", "dflt_value", "pk"]) for r in self._cur.fetchall()]
        elif name in ("quick_check", "integrity_check"):
            self._cur.execute("SELECT 'ok'")
            self._rows = [PgRow(r, ["result"]) for r in self._cur.fetchall()]
        else:
            self._rows = []               # journal_mode / foreign_keys / synchronous / query_only: không áp dụng
        return self

    def executemany(self, sql: str, seq: Iterable[Any]) -> "PgCursor":
        seq = [_params(p) for p in seq]
        q = translate(sql, True)
        ins = _INSERT_RE.match(q)
        if ins and ins.group(2):
            q = self._insert_or(q, ins, ins.group(3))
        self._run(q, seq, many=True)
        self.rowcount = self._cur.rowcount
        return self

    def executescript(self, script: str) -> "PgCursor":
        stmt, out = [], []
        for chunk, quoted in _outside_quotes(script):
            if quoted:
                stmt.append(chunk)
                continue
            pieces = chunk.split(";")
            for i, piece in enumerate(pieces):
                stmt.append(piece)
                if i < len(pieces) - 1:
                    out.append("".join(stmt))
                    stmt = []
        out.append("".join(stmt))
        for s in out:
            if s.strip():
                self.execute(s)
        return self

    # -- đọc
    def _materialize(self) -> List[PgRow]:
        if self._rows is None:
            if self._cur.description is None:
                self._rows = []
            else:
                names = [d.name for d in self._cur.description]
                self._rows = [PgRow(r, names) for r in self._cur.fetchall()]
        return self._rows

    def fetchone(self):
        rows = self._materialize()
        if self._pos >= len(rows):
            return None
        self._pos += 1
        return rows[self._pos - 1]

    def fetchall(self):
        rows = self._materialize()
        out, self._pos = rows[self._pos:], len(rows)
        return out

    def fetchmany(self, size: int = 1):
        rows = self._materialize()
        out = rows[self._pos:self._pos + size]
        self._pos += len(out)
        return out

    def __iter__(self):
        return iter(self.fetchall())

    def close(self) -> None:
        self._cur.close()


class PgConnection:
    """Giống ClosingConnection: thoát khối `with` = commit (hoặc rollback) rồi TRẢ kết nối."""

    def __init__(self, raw, schema: str, release) -> None:
        self._raw = raw
        self.schema = schema
        self._release = release
        self.row_factory = None
        self.closed = False

    def cursor(self) -> PgCursor:
        return PgCursor(self)

    def execute(self, sql: str, params: Any = None) -> PgCursor:
        return self.cursor().execute(sql, params)

    def executemany(self, sql: str, seq: Iterable[Any]) -> PgCursor:
        return self.cursor().executemany(sql, seq)

    def executescript(self, script: str) -> PgCursor:
        return self.cursor().executescript(script)

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def set_read_only(self, statement_timeout_ms: int = 5000) -> None:
        """Hộp cát cho SQL do LLM sinh: transaction CHỈ ĐỌC + giới hạn thời gian (thay authorizer SQLite)."""
        self._raw.execute("SET TRANSACTION READ ONLY")
        self._raw.execute(f"SET LOCAL statement_timeout = {int(statement_timeout_ms)}")

    def close(self) -> None:
        if not self.closed:
            self.closed = True
            self._release(self._raw)

    def __enter__(self) -> "PgConnection":
        return self

    def __exit__(self, exc_type, exc, tb) -> bool:
        try:
            if exc_type is None:
                self._raw.commit()
            else:
                self._raw.rollback()
        finally:
            self.close()
        return False


# ── Pool + chọn backend ──────────────────────────────────────────────────────

_POOLS: Dict[str, Any] = {}
_POOLS_LOCK = threading.Lock()


def database_url() -> str:
    import os
    url = os.environ.get("VNMATEAI_DATABASE_URL", "")
    if url.strip().lower() == "sqlite":          # ép SQLite (bộ test, bản lùi) dù config.json có DATABASE_URL
        return ""
    if not url:
        try:
            from mateai.config.loader import settings
            url = str(getattr(settings, "DATABASE_URL", "") or "")
        except Exception:  # noqa: BLE001
            url = ""
    return url if url.startswith(("postgresql://", "postgres://")) else ""


def schema_for(sqlite_path: Any) -> str:
    """Mỗi FILE SQLite cũ -> một schema PostgreSQL (giữ nguyên tính cô lập "mỗi file một DB"):
    vnmateai.db -> schema chính, hr_kpi.db -> schema nhân sự, đường dẫn khác -> schema riêng theo
    băm đường dẫn (DB tạm của công cụ / test không lẫn vào dữ liệu thật)."""
    import hashlib
    import os
    from pathlib import Path
    main = os.environ.get("VNMATEAI_PG_SCHEMA", "vnmate")
    hr = os.environ.get("VNMATEAI_PG_HR_SCHEMA", "hr")
    p = Path(str(sqlite_path)).resolve()
    from mateai.config.loader import settings
    root = Path(settings.PROJECT_ROOT).resolve()     # một nguồn thư mục gốc
    mains = {root / "vnmateai.db"}
    hrs = {root / "hr_kpi.db"}
    if os.environ.get("VNMATEAI_DB_PATH"):
        mains.add(Path(os.environ["VNMATEAI_DB_PATH"]).resolve())
    if os.environ.get("VNMATEAI_HR_DB_PATH"):
        hrs.add(Path(os.environ["VNMATEAI_HR_DB_PATH"]).resolve())
    if p in mains:
        return main
    if p in hrs:
        return hr
    return f"{main}_f{hashlib.sha1(str(p).lower().encode('utf-8')).hexdigest()[:10]}"


def connect(sqlite_path: Any, timeout: float = 30.0) -> PgConnection:
    from psycopg_pool import ConnectionPool
    url, schema = database_url(), schema_for(sqlite_path)
    key = f"{url}#{schema}"
    with _POOLS_LOCK:
        pool = _POOLS.get(key)
        if pool is None:
            def _configure(conn):
                import psycopg
                try:
                    conn.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
                    conn.commit()
                except psycopg.errors.UniqueViolation:
                    conn.rollback()      # pool khác vừa tạo cùng lúc (race của CREATE SCHEMA IF NOT EXISTS)
                conn.execute(f'SET search_path TO "{schema}"')
                conn.commit()
            pool = ConnectionPool(url, min_size=1, max_size=10, timeout=timeout, configure=_configure,
                                  kwargs={"connect_timeout": 10}, open=True)
            _POOLS[key] = pool
    raw = pool.getconn(timeout=timeout)

    def _release(c):
        try:
            if c.info.transaction_status != 0:      # còn transaction dở -> huỷ trước khi trả
                c.rollback()
        except Exception:  # noqa: BLE001
            pass
        pool.putconn(c)

    return PgConnection(raw, schema, _release)


def close_pools() -> None:
    with _POOLS_LOCK:
        for p in _POOLS.values():
            try:
                p.close()
            except Exception:  # noqa: BLE001
                pass
        _POOLS.clear()
    clear_catalog_cache()
