"""
mateai/infrastructure/database/pg_migration.py
==============================================
Di trú SQLite -> PostgreSQL theo giai đoạn (prompt cuối §66):

    schema_map()  bản đồ bảng / cột / khoá chính / index, kiểu đích
    migrate()     tạo schema đích + chép dữ liệu trong MỘT transaction (lỗi = không để lại gì)
    verify()      đối chiếu số dòng + checksum từng bảng giữa hai bên
    rollback()    xoá schema đích (SQLite nguồn không bị đụng tới)

SQLite vẫn là nguồn sự thật cho tới khi chuyển hẳn (cutover) — công cụ này KHÔNG xoá, không sửa
SQLite. Luật audit chỉ-ghi-thêm được dựng lại bằng trigger trên PostgreSQL.
Dòng lệnh: `python scripts/migrate_sqlite_to_pg.py --help`.
"""
from __future__ import annotations

import hashlib
import re
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

BATCH = 2000


class MigrationError(RuntimeError):
    pass


def _pg_type(declared: str) -> str:
    """Một nguồn ánh xạ kiểu với DDL lúc chạy (pg_compat) — hai bên không được lệch."""
    from mateai.infrastructure.database.pg_compat import sqlite_type_to_pg
    return sqlite_type_to_pg(declared)


def _q(name: str) -> str:
    return '"' + str(name).replace('"', '""') + '"'


def _open(path: Path):
    # Luôn đọc FILE SQLite thật (kể cả khi ứng dụng đã chạy trên PostgreSQL).
    from mateai.infrastructure.database.erp_database import open_sqlite_file
    return open_sqlite_file(path, timeout=30.0)


def schema_map(sqlite_path: Path) -> List[Dict[str, Any]]:
    conn = _open(Path(sqlite_path))
    try:
        tables = [r[0] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name;")]
        plan = []
        for t in tables:
            sql = (conn.execute("SELECT sql FROM sqlite_master WHERE type='table' AND name=?;", (t,)).fetchone()[0]
                   or "")
            info = conn.execute(f"PRAGMA table_info({_q(t)});").fetchall()
            pk = [r[1] for r in sorted(info, key=lambda r: r[5]) if r[5]]
            cols = []
            for cid, name, decl, notnull, dflt, pkpos in info:
                pg = _pg_type(decl)
                identity = (len(pk) == 1 and pk[0] == name and pg == "BIGINT"
                            and ("AUTOINCREMENT" in sql.upper() or "INTEGER" in (decl or "").upper()))
                cols.append({"name": name, "sqlite_type": decl, "pg_type": pg, "not_null": bool(notnull),
                             "default": dflt, "identity": identity})
            indexes = [r[0] for r in conn.execute(
                "SELECT sql FROM sqlite_master WHERE type='index' AND tbl_name=? AND sql IS NOT NULL;", (t,))]
            fks = [{"from": r[3], "table": r[2], "to": r[4], "on_delete": r[6]}
                   for r in conn.execute(f"PRAGMA foreign_key_list({_q(t)});").fetchall()]
            plan.append({"table": t, "columns": cols, "primary_key": pk, "indexes": indexes, "foreign_keys": fks})
        return plan
    finally:
        conn.close()


def _default_sql(dflt: Optional[str]) -> Optional[str]:
    if dflt is None:
        return None
    d = str(dflt).strip()
    if re.fullmatch(r"-?\d+(\.\d+)?", d) or re.fullmatch(r"'(?:[^']|'')*'", d):
        return d
    if d.upper() == "CURRENT_TIMESTAMP":
        return "to_char(now(), 'YYYY-MM-DD HH24:MI:SS')"
    return None          # biểu thức riêng của SQLite: bỏ, ứng dụng tự điền giá trị


def _create_table_sql(schema: str, t: Dict[str, Any]) -> str:
    parts = []
    for c in t["columns"]:
        if c["identity"]:
            parts.append(f"{_q(c['name'])} BIGINT GENERATED BY DEFAULT AS IDENTITY")
            continue
        p = f"{_q(c['name'])} {c['pg_type']}"
        if c["not_null"]:
            p += " NOT NULL"
        d = _default_sql(c["default"])
        if d is not None:
            p += f" DEFAULT {d}"
        parts.append(p)
    if t["primary_key"]:
        parts.append("PRIMARY KEY (" + ", ".join(_q(k) for k in t["primary_key"]) + ")")
    return f"CREATE TABLE {_q(schema)}.{_q(t['table'])} (" + ", ".join(parts) + ");"


_INDEX_RE = re.compile(r"CREATE\s+(UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?(\S+)\s+ON\s+(\S+)\s*\((.+)\)\s*;?\s*$",
                       re.IGNORECASE | re.DOTALL)


def _index_sql(schema: str, sql: str) -> Optional[str]:
    m = _INDEX_RE.match(sql.strip())
    if not m:
        return None
    unique, name, table, cols = m.groups()
    name, table = name.strip('"[]`'), table.strip('"[]`')
    # Giữ nguyên tên index (duy nhất trong schema) — ứng dụng chạy `CREATE INDEX IF NOT EXISTS <tên>`
    # lúc khởi động; đổi tên ở đây sẽ sinh index trùng.
    return (f"CREATE {'UNIQUE ' if unique else ''}INDEX IF NOT EXISTS {_q(name)} "
            f"ON {_q(schema)}.{_q(table)} ({cols});")


def _convert(v: Any, pg_type: str, where: str) -> Any:
    if v is None:
        return None
    try:
        if pg_type == "BIGINT":
            return int(v) if not isinstance(v, bool) else int(v)
        if pg_type == "DOUBLE PRECISION":
            return float(v)
        if pg_type == "BYTEA":
            return bytes(v) if isinstance(v, (bytes, bytearray, memoryview)) else str(v).encode("utf-8")
        if pg_type == "NUMERIC":
            return str(v)
        return v if isinstance(v, str) else (bytes(v).decode("utf-8", "replace")
                                              if isinstance(v, (bytes, memoryview)) else str(v))
    except (TypeError, ValueError) as exc:
        # Không ép bừa: dữ liệu sai kiểu phải được nhìn thấy, không chép lệch.
        raise MigrationError(f"{where}: giá trị {v!r} không chuyển được sang {pg_type}") from exc


def _norm(v: Any, pg_type: str) -> str:
    if v is None:
        return "\\N"
    if pg_type == "BIGINT":
        return str(int(v))
    if pg_type == "DOUBLE PRECISION":
        return repr(float(v))
    if pg_type == "BYTEA":
        return (bytes(v) if not isinstance(v, str) else v.encode("utf-8")).hex()
    return str(v)


def _checksum(rows: Iterable[tuple], types: List[str]) -> str:
    lines = sorted("\x1f".join(_norm(v, t) for v, t in zip(r, types)) for r in rows)
    h = hashlib.sha256()
    for line in lines:
        h.update(line.encode("utf-8"))
        h.update(b"\x1e")
    return h.hexdigest()


def _schema_exists(conn, schema: str) -> bool:
    return bool(conn.execute("SELECT 1 FROM information_schema.schemata WHERE schema_name = %s", (schema,)).fetchone())


def migrate(sqlite_path: Path, pg_dsn: str, schema: str = "vnmate", replace: bool = False) -> Dict[str, Any]:
    import psycopg
    t0 = time.perf_counter()
    plan = schema_map(sqlite_path)
    skipped_indexes: List[str] = []
    src = _open(Path(sqlite_path))
    try:
        with psycopg.connect(pg_dsn) as pg:              # một transaction: lỗi -> không để lại gì
            if _schema_exists(pg, schema):
                if not replace:
                    raise MigrationError(f"Schema '{schema}' đã tồn tại — dùng replace=True (--replace) "
                                         "hoặc rollback trước.")
                pg.execute(f"DROP SCHEMA {_q(schema)} CASCADE")
            pg.execute(f"CREATE SCHEMA {_q(schema)}")
            for t in plan:
                pg.execute(_create_table_sql(schema, t))
                names = [c["name"] for c in t["columns"]]
                types = [c["pg_type"] for c in t["columns"]]
                cur = src.execute(f"SELECT {', '.join(_q(n) for n in names)} FROM {_q(t['table'])};")
                with pg.cursor() as pc:
                    with pc.copy(f"COPY {_q(schema)}.{_q(t['table'])} ({', '.join(_q(n) for n in names)}) "
                                 "FROM STDIN") as cp:
                        while True:
                            batch = cur.fetchmany(BATCH)
                            if not batch:
                                break
                            for row in batch:
                                cp.write_row([_convert(v, ty, f"{t['table']}.{n}")
                                              for v, ty, n in zip(tuple(row), types, names)])
                for c in t["columns"]:
                    if c["identity"]:
                        pg.execute(f"SELECT setval(pg_get_serial_sequence('{schema}.{t['table']}', %s), "
                                   f"COALESCE((SELECT max({_q(c['name'])}) FROM {_q(schema)}.{_q(t['table'])}), 0) + 1,"
                                   " false)", (c["name"],))
                for isql in t["indexes"]:
                    stmt = _index_sql(schema, isql)
                    if stmt:
                        pg.execute(stmt)
                    else:
                        skipped_indexes.append(isql)
                if t["table"] == "audit_logs":
                    # Cùng tên hàm / trigger với lúc chạy (erp_database._create_audit_guards).
                    pg.execute(f"""
                        CREATE OR REPLACE FUNCTION {_q(schema)}.audit_logs_append_only() RETURNS trigger AS $$
                        BEGIN RAISE EXCEPTION 'audit_logs là append-only: không được sửa / xoá'; END
                        $$ LANGUAGE plpgsql;""")
                    for trg, ev in (("audit_logs_no_update", "UPDATE"), ("audit_logs_no_delete", "DELETE")):
                        pg.execute(f"CREATE OR REPLACE TRIGGER {trg} BEFORE {ev} ON {_q(schema)}.audit_logs "
                                   f"FOR EACH ROW EXECUTE FUNCTION {_q(schema)}.audit_logs_append_only();")
            # Khoá ngoại sau khi đủ bảng + dữ liệu (ON DELETE CASCADE / SET NULL mà ứng dụng dựa vào).
            fk_skipped = []
            for t in plan:
                for fk in t.get("foreign_keys") or []:
                    name = f"fk_{t['table']}_{fk['from']}"
                    on_del = fk["on_delete"] if fk["on_delete"] and fk["on_delete"] != "NO ACTION" else ""
                    stmt = (f"ALTER TABLE {_q(schema)}.{_q(t['table'])} ADD CONSTRAINT {_q(name)} "
                            f"FOREIGN KEY ({_q(fk['from'])}) REFERENCES {_q(schema)}.{_q(fk['table'])} ({_q(fk['to'])})"
                            + (f" ON DELETE {on_del}" if on_del else ""))
                    try:
                        with pg.transaction():
                            pg.execute(stmt)
                    except psycopg.Error as exc:
                        # Dữ liệu cũ vi phạm (bản ghi mồ côi): gắn NOT VALID — ràng buộc áp cho dữ liệu MỚI.
                        try:
                            with pg.transaction():
                                pg.execute(stmt + " NOT VALID")
                            fk_skipped.append({"constraint": name, "note": f"NOT VALID: {exc}".splitlines()[0]})
                        except psycopg.Error as exc2:
                            fk_skipped.append({"constraint": name, "note": str(exc2).splitlines()[0]})
    finally:
        src.close()
    rep = verify(sqlite_path, pg_dsn, schema, plan=plan)
    rep.update({"duration_s": round(time.perf_counter() - t0, 2), "skipped_indexes": skipped_indexes,
                "foreign_keys_not_validated": fk_skipped})
    return rep


def verify(sqlite_path: Path, pg_dsn: str, schema: str = "vnmate",
           plan: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    import psycopg
    plan = plan or schema_map(sqlite_path)
    tables, mismatches = [], []
    src = _open(Path(sqlite_path))
    try:
        with psycopg.connect(pg_dsn, autocommit=True) as pg:
            for t in plan:
                names = [c["name"] for c in t["columns"]]
                types = [c["pg_type"] for c in t["columns"]]
                cols = ", ".join(_q(n) for n in names)
                s_rows = [tuple(r) for r in src.execute(f"SELECT {cols} FROM {_q(t['table'])};")]
                try:
                    p_rows = pg.execute(f"SELECT {cols} FROM {_q(schema)}.{_q(t['table'])}").fetchall()
                except psycopg.Error as exc:
                    mismatches.append({"table": t["table"], "problem": f"không đọc được bên PostgreSQL: {exc}"})
                    continue
                row = {"table": t["table"], "rows_sqlite": len(s_rows), "rows_pg": len(p_rows),
                       "checksum_sqlite": _checksum(s_rows, types), "checksum_pg": _checksum(p_rows, types)}
                tables.append(row)
                if row["rows_sqlite"] != row["rows_pg"]:
                    mismatches.append({"table": t["table"], "problem": "lệch số dòng"})
                elif row["checksum_sqlite"] != row["checksum_pg"]:
                    mismatches.append({"table": t["table"], "problem": "lệch nội dung (checksum)"})
    finally:
        src.close()
    return {"ok": not mismatches, "tables": tables, "mismatches": mismatches, "schema": schema}


_PG_TO_SQLITE = {"bigint": "INTEGER", "integer": "INTEGER", "smallint": "INTEGER", "boolean": "INTEGER",
                 "double precision": "REAL", "real": "REAL", "numeric": "NUMERIC", "bytea": "BLOB"}


def _sqlite_default(pg_default: Optional[str]) -> Optional[str]:
    """Mặc định cột PostgreSQL -> SQLite (chỉ hằng số + thời điểm hiện tại; còn lại bỏ)."""
    if not pg_default or "nextval(" in pg_default:
        return None
    d = re.sub(r"::[A-Za-z ]+$", "", pg_default.strip())
    if d.startswith("to_char(now()"):
        return "CURRENT_TIMESTAMP"
    if re.fullmatch(r"-?\d+(\.\d+)?", d) or re.fullmatch(r"'(?:[^']|'')*'", d):
        return d
    return None


_PG_INDEX_RE = re.compile(r"CREATE\s+(UNIQUE\s+)?INDEX\s+(\S+)\s+ON\s+\S+\s+USING\s+btree\s+\((.+)\)\s*$", re.I)


def export_to_sqlite(pg_dsn: str, schema: str, sqlite_path: Path) -> Dict[str, Any]:
    """Chụp MỘT schema PostgreSQL ra file SQLite (đường lùi + định dạng sao lưu chung).

    Đọc trong một transaction REPEATABLE READ READ ONLY -> bản chụp nhất quán kể cả khi máy chủ đang
    ghi. File ra dùng lại được bằng `migrate(..., replace=True)` (khôi phục) — cùng đường kiểm chứng
    checksum. Trả số dòng + checksum từng bảng tính TRONG bản chụp, đã đối chiếu với file vừa ghi."""
    import psycopg
    from mateai.infrastructure.database.erp_database import open_sqlite_file
    sqlite_path = Path(sqlite_path)
    if sqlite_path.exists():
        raise MigrationError(f"{sqlite_path} đã tồn tại — không ghi đè")
    out = open_sqlite_file(sqlite_path, wal=False)      # một file duy nhất, không kèm -wal
    tables: List[Dict[str, Any]] = []
    try:
        with psycopg.connect(pg_dsn) as pg:
            pg.execute("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY")
            if not _schema_exists(pg, schema):
                raise MigrationError(f"Schema '{schema}' không tồn tại")
            names = [r[0] for r in pg.execute(
                "SELECT table_name FROM information_schema.tables WHERE table_schema = %s "
                "AND table_type = 'BASE TABLE' ORDER BY table_name", (schema,))]
            for t in names:
                cols = pg.execute(
                    "SELECT column_name, data_type, is_nullable, column_default, is_identity "
                    "FROM information_schema.columns WHERE table_schema = %s AND table_name = %s "
                    "ORDER BY ordinal_position", (schema, t)).fetchall()
                pk = [r[0] for r in pg.execute(
                    "SELECT a.attname FROM pg_index i JOIN pg_attribute a ON a.attrelid = i.indrelid "
                    "AND a.attnum = ANY(i.indkey) WHERE i.indrelid = %s::regclass AND i.indisprimary "
                    "ORDER BY array_position(i.indkey, a.attnum)", (f'{_q(schema)}.{_q(t)}',))]
                fks = pg.execute(
                    "SELECT kcu.column_name, ccu.table_name, ccu.column_name, rc.delete_rule "
                    "FROM information_schema.referential_constraints rc "
                    "JOIN information_schema.key_column_usage kcu ON kcu.constraint_name = rc.constraint_name "
                    " AND kcu.constraint_schema = rc.constraint_schema "
                    "JOIN information_schema.constraint_column_usage ccu ON ccu.constraint_name = rc.unique_constraint_name "
                    " AND ccu.constraint_schema = rc.unique_constraint_schema "
                    "WHERE rc.constraint_schema = %s AND kcu.table_name = %s", (schema, t)).fetchall()
                parts, types = [], []
                for name, dtype, nullable, dflt, ident in cols:
                    st = _PG_TO_SQLITE.get(dtype, "TEXT")
                    types.append(_pg_type(st))
                    if ident == "YES" and pk == [name]:
                        parts.append(f"{_q(name)} INTEGER PRIMARY KEY AUTOINCREMENT")
                        continue
                    p = f"{_q(name)} {st}"
                    if nullable == "NO":
                        p += " NOT NULL"
                    d = _sqlite_default(dflt)
                    if d is not None:
                        p += f" DEFAULT {d}"
                    parts.append(p)
                if pk and not any("PRIMARY KEY" in p for p in parts):
                    parts.append("PRIMARY KEY (" + ", ".join(_q(k) for k in pk) + ")")
                for col, rt, rc, rule in fks:
                    parts.append(f"FOREIGN KEY ({_q(col)}) REFERENCES {_q(rt)} ({_q(rc)})"
                                 + (f" ON DELETE {rule}" if rule and rule != "NO ACTION" else ""))
                out.execute(f"CREATE TABLE {_q(t)} (" + ", ".join(parts) + ")")
                colnames = [c[0] for c in cols]
                rows = pg.execute(f"SELECT {', '.join(_q(n) for n in colnames)} FROM {_q(schema)}.{_q(t)}").fetchall()
                conv = [tuple(str(v) if type(v).__name__ == "Decimal" else v for v in r) for r in rows]
                out.executemany(f"INSERT INTO {_q(t)} VALUES ({', '.join('?' for _ in colnames)})", conv)
                for (idxdef,) in pg.execute("SELECT indexdef FROM pg_indexes WHERE schemaname = %s AND tablename = %s "
                                            "AND indexname NOT IN (SELECT conname FROM pg_constraint "
                                            "WHERE connamespace = %s::regnamespace)", (schema, t, _q(schema))):
                    m = _PG_INDEX_RE.match(idxdef)
                    if m:
                        out.execute(f"CREATE {'UNIQUE ' if m.group(1) else ''}INDEX IF NOT EXISTS "
                                    f"{_q(m.group(2).strip(chr(34)))} ON {_q(t)} ({m.group(3)})")
                tables.append({"table": t, "rows": len(rows), "checksum": _checksum(rows, types),
                               "_cols": colnames, "_types": types})
            pg.rollback()
        out.commit()
        mismatches = []
        for t in tables:
            back = [tuple(r) for r in out.execute(f"SELECT {', '.join(_q(n) for n in t.pop('_cols'))} FROM {_q(t['table'])}")]
            if len(back) != t["rows"] or _checksum(back, t.pop("_types")) != t["checksum"]:
                mismatches.append(t["table"])
    finally:
        out.close()
    if mismatches:
        raise MigrationError("Bản chụp SQLite lệch PostgreSQL ở: " + ", ".join(mismatches))
    return {"ok": True, "schema": schema, "tables": tables}


def rollback(pg_dsn: str, schema: str = "vnmate") -> None:
    import psycopg
    with psycopg.connect(pg_dsn, autocommit=True) as pg:
        pg.execute(f"DROP SCHEMA IF EXISTS {_q(schema)} CASCADE")
