"""
mateai/infrastructure/database/pg_migration.py
==============================================
Di trú SQLite -> PostgreSQL theo giai đoạn (prompt cuối §66):

    schema_map()  bản đồ bảng / cột / khoá chính / index, kiểu đích
    migrate()     tạo schema đích + chép dữ liệu trong MỘT transaction (lỗi = không để lại gì)
    verify()      đối chiếu số dòng + checksum từng bảng giữa hai bên
    rollback()    xoá schema đích (SQLite nguồn không bị đụng tới)

SQLite vẫn là nguồn sự thật cho tới khi chuyển hẳn (cutover) — công cụ này KHÔNG xoá, không sửa
SQLite. Luật audit chỉ-ghi-thêm được dựng lại bằng trigger trên PostgreSQL.
Dòng lệnh: `python scripts/migrate_sqlite_to_pg.py --help`.
"""
from __future__ import annotations

import hashlib
import re
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

BATCH = 2000


class MigrationError(RuntimeError):
    pass


def _pg_type(declared: str) -> str:
    """Theo quy tắc type affinity của SQLite."""
    t = (declared or "").upper()
    if "INT" in t:
        return "BIGINT"
    if any(k in t for k in ("CHAR", "CLOB", "TEXT")):
        return "TEXT"
    if "BLOB" in t:
        return "BYTEA"
    if any(k in t for k in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if any(k in t for k in ("NUMERIC", "DECIMAL")):
        return "NUMERIC"
    return "TEXT"


def _q(name: str) -> str:
    return '"' + str(name).replace('"', '""') + '"'


def _open(path: Path):
    from mateai.infrastructure.database.erp_database import open_sqlite
    return open_sqlite(path, timeout=30.0)


def schema_map(sqlite_path: Path) -> List[Dict[str, Any]]:
    conn = _open(Path(sqlite_path))
    try:
        tables = [r[0] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name;")]
        plan = []
        for t in tables:
            sql = (conn.execute("SELECT sql FROM sqlite_master WHERE type='table' AND name=?;", (t,)).fetchone()[0]
                   or "")
            info = conn.execute(f"PRAGMA table_info({_q(t)});").fetchall()
            pk = [r[1] for r in sorted(info, key=lambda r: r[5]) if r[5]]
            cols = []
            for cid, name, decl, notnull, dflt, pkpos in info:
                pg = _pg_type(decl)
                identity = (len(pk) == 1 and pk[0] == name and pg == "BIGINT"
                            and ("AUTOINCREMENT" in sql.upper() or "INTEGER" in (decl or "").upper()))
                cols.append({"name": name, "sqlite_type": decl, "pg_type": pg, "not_null": bool(notnull),
                             "default": dflt, "identity": identity})
            indexes = [r[0] for r in conn.execute(
                "SELECT sql FROM sqlite_master WHERE type='index' AND tbl_name=? AND sql IS NOT NULL;", (t,))]
            plan.append({"table": t, "columns": cols, "primary_key": pk, "indexes": indexes})
        return plan
    finally:
        conn.close()


def _default_sql(dflt: Optional[str]) -> Optional[str]:
    if dflt is None:
        return None
    d = str(dflt).strip()
    if re.fullmatch(r"-?\d+(\.\d+)?", d) or re.fullmatch(r"'(?:[^']|'')*'", d):
        return d
    if d.upper() == "CURRENT_TIMESTAMP":
        return "to_char(now(), 'YYYY-MM-DD HH24:MI:SS')"
    return None          # biểu thức riêng của SQLite: bỏ, ứng dụng tự điền giá trị


def _create_table_sql(schema: str, t: Dict[str, Any]) -> str:
    parts = []
    for c in t["columns"]:
        if c["identity"]:
            parts.append(f"{_q(c['name'])} BIGINT GENERATED BY DEFAULT AS IDENTITY")
            continue
        p = f"{_q(c['name'])} {c['pg_type']}"
        if c["not_null"]:
            p += " NOT NULL"
        d = _default_sql(c["default"])
        if d is not None:
            p += f" DEFAULT {d}"
        parts.append(p)
    if t["primary_key"]:
        parts.append("PRIMARY KEY (" + ", ".join(_q(k) for k in t["primary_key"]) + ")")
    return f"CREATE TABLE {_q(schema)}.{_q(t['table'])} (" + ", ".join(parts) + ");"


_INDEX_RE = re.compile(r"CREATE\s+(UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?(\S+)\s+ON\s+(\S+)\s*\((.+)\)\s*;?\s*$",
                       re.IGNORECASE | re.DOTALL)


def _index_sql(schema: str, sql: str) -> Optional[str]:
    m = _INDEX_RE.match(sql.strip())
    if not m:
        return None
    unique, name, table, cols = m.groups()
    name, table = name.strip('"[]`'), table.strip('"[]`')
    return (f"CREATE {'UNIQUE ' if unique else ''}INDEX IF NOT EXISTS {_q(schema + '_' + name)} "
            f"ON {_q(schema)}.{_q(table)} ({cols});")


def _convert(v: Any, pg_type: str, where: str) -> Any:
    if v is None:
        return None
    try:
        if pg_type == "BIGINT":
            return int(v) if not isinstance(v, bool) else int(v)
        if pg_type == "DOUBLE PRECISION":
            return float(v)
        if pg_type == "BYTEA":
            return bytes(v) if isinstance(v, (bytes, bytearray, memoryview)) else str(v).encode("utf-8")
        if pg_type == "NUMERIC":
            return str(v)
        return v if isinstance(v, str) else (bytes(v).decode("utf-8", "replace")
                                              if isinstance(v, (bytes, memoryview)) else str(v))
    except (TypeError, ValueError) as exc:
        # Không ép bừa: dữ liệu sai kiểu phải được nhìn thấy, không chép lệch.
        raise MigrationError(f"{where}: giá trị {v!r} không chuyển được sang {pg_type}") from exc


def _norm(v: Any, pg_type: str) -> str:
    if v is None:
        return "\\N"
    if pg_type == "BIGINT":
        return str(int(v))
    if pg_type == "DOUBLE PRECISION":
        return repr(float(v))
    if pg_type == "BYTEA":
        return (bytes(v) if not isinstance(v, str) else v.encode("utf-8")).hex()
    return str(v)


def _checksum(rows: Iterable[tuple], types: List[str]) -> str:
    lines = sorted("\x1f".join(_norm(v, t) for v, t in zip(r, types)) for r in rows)
    h = hashlib.sha256()
    for line in lines:
        h.update(line.encode("utf-8"))
        h.update(b"\x1e")
    return h.hexdigest()


def _schema_exists(conn, schema: str) -> bool:
    return bool(conn.execute("SELECT 1 FROM information_schema.schemata WHERE schema_name = %s", (schema,)).fetchone())


def migrate(sqlite_path: Path, pg_dsn: str, schema: str = "vnmate", replace: bool = False) -> Dict[str, Any]:
    import psycopg
    t0 = time.perf_counter()
    plan = schema_map(sqlite_path)
    skipped_indexes: List[str] = []
    src = _open(Path(sqlite_path))
    try:
        with psycopg.connect(pg_dsn) as pg:              # một transaction: lỗi -> không để lại gì
            if _schema_exists(pg, schema):
                if not replace:
                    raise MigrationError(f"Schema '{schema}' đã tồn tại — dùng replace=True (--replace) "
                                         "hoặc rollback trước.")
                pg.execute(f"DROP SCHEMA {_q(schema)} CASCADE")
            pg.execute(f"CREATE SCHEMA {_q(schema)}")
            for t in plan:
                pg.execute(_create_table_sql(schema, t))
                names = [c["name"] for c in t["columns"]]
                types = [c["pg_type"] for c in t["columns"]]
                cur = src.execute(f"SELECT {', '.join(_q(n) for n in names)} FROM {_q(t['table'])};")
                with pg.cursor() as pc:
                    with pc.copy(f"COPY {_q(schema)}.{_q(t['table'])} ({', '.join(_q(n) for n in names)}) "
                                 "FROM STDIN") as cp:
                        while True:
                            batch = cur.fetchmany(BATCH)
                            if not batch:
                                break
                            for row in batch:
                                cp.write_row([_convert(v, ty, f"{t['table']}.{n}")
                                              for v, ty, n in zip(tuple(row), types, names)])
                for c in t["columns"]:
                    if c["identity"]:
                        pg.execute(f"SELECT setval(pg_get_serial_sequence('{schema}.{t['table']}', %s), "
                                   f"COALESCE((SELECT max({_q(c['name'])}) FROM {_q(schema)}.{_q(t['table'])}), 0) + 1,"
                                   " false)", (c["name"],))
                for isql in t["indexes"]:
                    stmt = _index_sql(schema, isql)
                    if stmt:
                        pg.execute(stmt)
                    else:
                        skipped_indexes.append(isql)
                if t["table"] == "audit_logs":
                    pg.execute(f"""
                        CREATE FUNCTION {_q(schema)}.audit_logs_append_only() RETURNS trigger AS $$
                        BEGIN RAISE EXCEPTION 'audit_logs là append-only: không được sửa / xoá'; END
                        $$ LANGUAGE plpgsql;""")
                    pg.execute(f"CREATE TRIGGER audit_logs_append_only BEFORE UPDATE OR DELETE "
                               f"ON {_q(schema)}.audit_logs FOR EACH ROW "
                               f"EXECUTE FUNCTION {_q(schema)}.audit_logs_append_only();")
    finally:
        src.close()
    rep = verify(sqlite_path, pg_dsn, schema, plan=plan)
    rep.update({"duration_s": round(time.perf_counter() - t0, 2), "skipped_indexes": skipped_indexes})
    return rep


def verify(sqlite_path: Path, pg_dsn: str, schema: str = "vnmate",
           plan: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    import psycopg
    plan = plan or schema_map(sqlite_path)
    tables, mismatches = [], []
    src = _open(Path(sqlite_path))
    try:
        with psycopg.connect(pg_dsn, autocommit=True) as pg:
            for t in plan:
                names = [c["name"] for c in t["columns"]]
                types = [c["pg_type"] for c in t["columns"]]
                cols = ", ".join(_q(n) for n in names)
                s_rows = [tuple(r) for r in src.execute(f"SELECT {cols} FROM {_q(t['table'])};")]
                try:
                    p_rows = pg.execute(f"SELECT {cols} FROM {_q(schema)}.{_q(t['table'])}").fetchall()
                except psycopg.Error as exc:
                    mismatches.append({"table": t["table"], "problem": f"không đọc được bên PostgreSQL: {exc}"})
                    continue
                row = {"table": t["table"], "rows_sqlite": len(s_rows), "rows_pg": len(p_rows),
                       "checksum_sqlite": _checksum(s_rows, types), "checksum_pg": _checksum(p_rows, types)}
                tables.append(row)
                if row["rows_sqlite"] != row["rows_pg"]:
                    mismatches.append({"table": t["table"], "problem": "lệch số dòng"})
                elif row["checksum_sqlite"] != row["checksum_pg"]:
                    mismatches.append({"table": t["table"], "problem": "lệch nội dung (checksum)"})
    finally:
        src.close()
    return {"ok": not mismatches, "tables": tables, "mismatches": mismatches, "schema": schema}


def rollback(pg_dsn: str, schema: str = "vnmate") -> None:
    import psycopg
    with psycopg.connect(pg_dsn, autocommit=True) as pg:
        pg.execute(f"DROP SCHEMA IF EXISTS {_q(schema)} CASCADE")
