# Auto-synthesised skill: auto_get_server_uptime
# Generated by VN-MateAI MetaArchitect.
# Yêu cầu gốc: Kiểm tra thời gian hoạt động (uptime) của máy chủ hệ thống (sử dụng thư viện psutil hoặc lệnh hệ thống để lấy thời gian máy chủ đã chạy).

import datetime
import time
from typing import Any, Dict

import psutil

from core.plugin_manager import export_skill


@export_skill(
    name="get_system_uptime",
    description=(
        "Kiểm tra thời gian hoạt động (uptime) của hệ thống máy tính/máy chủ Windows, cho biết máy đã mở và chạy liên tục được bao lâu kể từ lần khởi động gần nhất. Các cách người dùng hay yêu cầu: 'kiểm tra uptime máy chủ', 'máy tính đã bật được bao lâu rồi', 'xem thời gian hoạt động của máy', 'máy chạy liên tục mấy ngày rồi', 'hệ thống khởi động lúc nào'. Keywords: system uptime, server uptime, boot time, check running time, system running duration. Ví dụ yêu cầu: «Kiểm tra thời gian hoạt động (uptime) của máy chủ hệ thống (sử dụng thư viện psutil hoặc lệnh hệ thống để lấy thời gian máy chủ đã chạy).»."
    ),
    parameters_schema={
        "type": "object",
        "properties": {},
        "required": [],
    },
)
def get_system_uptime() -> Dict[str, Any]:
    """Lấy thông tin thời gian khởi động và tổng thời gian hoạt động (uptime) của hệ thống."""
    try:
        boot_timestamp = psutil.boot_time()
        boot_datetime = datetime.datetime.fromtimestamp(boot_timestamp)
        now_datetime = datetime.datetime.now()

        total_seconds = int(time.time() - boot_timestamp)
        if total_seconds < 0:
            total_seconds = 0

        days, remainder = divmod(total_seconds, 86400)
        hours, remainder = divmod(remainder, 3600)
        minutes, seconds = divmod(remainder, 60)

        parts = []
        if days > 0:
            parts.append(f"{days} ngày")
        if hours > 0 or days > 0:
            parts.append(f"{hours} giờ")
        if minutes > 0 or hours > 0 or days > 0:
            parts.append(f"{minutes} phút")
        parts.append(f"{seconds} giây")

        uptime_readable = " ".join(parts)

        return {
            "success": True,
            "boot_time": boot_datetime.strftime("%Y-%m-%d %H:%M:%S"),
            "current_time": now_datetime.strftime("%Y-%m-%d %H:%M:%S"),
            "uptime_seconds": total_seconds,
            "uptime_formatted": uptime_readable,
            "details": {
                "days": days,
                "hours": hours,
                "minutes": minutes,
                "seconds": seconds,
            },
            "message": f"Hệ thống đã hoạt động liên tục được {uptime_readable} (khởi động lúc {boot_datetime.strftime('%H:%M:%S ngày %d/%m/%Y')}).",
        }
    except Exception as exc:
        return {
            "success": False,
            "error": f"Không thể lấy thời gian hoạt động của hệ thống: {str(exc)}",
        }
