# Auto-synthesised skill: auto_count_chrome_tabs
# Generated by VN-MateAI MetaArchitect.
# Yêu cầu gốc: Đếm số lượng tab (tabs) hoặc cửa sổ đang mở trên trình duyệt Google Chrome hoặc liệt kê các tab đang hoạt động.

import json
import subprocess
from typing import Any, Dict, List, Optional
from core.plugin_manager import export_skill


def _run_powershell_script(script: str) -> Optional[str]:
    """Thực thi đoạn mã PowerShell và trả về chuỗi kết quả stdout."""
    try:
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        startupinfo.wShowWindow = 0  # SW_HIDE

        process = subprocess.run(
            [
                "powershell.exe",
                "-NoProfile",
                "-NonInteractive",
                "-ExecutionPolicy",
                "Bypass",
                "-Command",
                script,
            ],
            capture_output=True,
            text=True,
            timeout=15,
            startupinfo=startupinfo,
            creationflags=subprocess.CREATE_NO_WINDOW,
        )

        if process.returncode == 0:
            return process.stdout.strip()
        return None
    except Exception:
        return None


@export_skill(
    name="get_chrome_tabs_info",
    description=(
        "Đếm số lượng tab và cửa sổ đang mở trên trình duyệt Google Chrome, đồng thời liệt kê tiêu đề của các tab đang hoạt động. Thường dùng khi người dùng nói: 'đếm số tab chrome đang mở', 'kiểm tra chrome có bao nhiêu tab', 'liệt kê các tab chrome', 'xem danh sách tab đang mở trên chrome', 'how many tabs are open in chrome', 'list chrome tabs'. Ví dụ yêu cầu: «Đếm số lượng tab (tabs) hoặc cửa sổ đang mở trên trình duyệt Google Chrome hoặc liệt kê các tab đang hoạt động.»."
    ),
    parameters_schema={
        "type": "object",
        "properties": {
            "include_tab_titles": {
                "type": "boolean",
                "description": "True nếu muốn lấy chi tiết tên tiêu đề của từng tab, False nếu chỉ cần đếm số lượng.",
                "default": True,
            }
        },
        "required": [],
    },
)
def get_chrome_tabs_info(include_tab_titles: bool = True) -> Dict[str, Any]:
    """
    Truy vấn và đếm số lượng cửa sổ cũng như các tab đang mở trong Google Chrome
    thông qua Windows UI Automation.
    """
    ps_script = """
Add-Type -AssemblyName UIAutomationClient
Add-Type -AssemblyName UIAutomationTypes

$condClass = New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::ClassNameProperty, 'Chrome_WidgetWin_1')
$windows = [System.Windows.Automation.AutomationElement]::RootElement.FindAll([System.Windows.Automation.TreeScope]::Children, $condClass)

$results = @()
$condTab = New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::ControlTypeProperty, [System.Windows.Automation.ControlType]::TabItem)

foreach ($w in $windows) {
    $wName = $w.Current.Name
    # Bỏ qua các cửa sổ phụ/ẩn hoặc tooltip không có title
    if ([string]::IsNullOrWhiteSpace($wName)) {
        continue
    }

    $tabs = $w.FindAll([System.Windows.Automation.TreeScope]::Descendants, $condTab)
    $tabList = @()
    if ($tabs -ne $null) {
        foreach ($t in $tabs) {
            $tName = $t.Current.Name
            if (-not [string]::IsNullOrWhiteSpace($tName)) {
                $tabList += $tName
            }
        }
    }

    # Chỉ ghi nhận nếu là cửa sổ chính có tabs hoặc có tiêu đề ứng dụng Chrome
    if ($tabList.Count -gt 0 -or $wName -match 'Google Chrome') {
        $results += [PSCustomObject]@{
            WindowTitle = $wName
            TabCount = $tabList.Count
            Tabs = $tabList
        }
    }
}

if ($results.Count -eq 0) {
    Write-Output "[]"
} else {
    $results | ConvertTo-Json -Depth 3 -Compress
}
"""

    try:
        raw_output = _run_powershell_script(ps_script)
        if not raw_output:
            return {
                "success": False,
                "error": "Không thể kết nối hoặc trình duyệt Google Chrome chưa được mở.",
                "total_windows": 0,
                "total_tabs": 0,
                "windows": [],
            }

        parsed_data = json.loads(raw_output)

        if isinstance(parsed_data, dict):
            windows_data = [parsed_data]
        elif isinstance(parsed_data, list):
            windows_data = parsed_data
        else:
            windows_data = []

        total_windows = len(windows_data)
        total_tabs = 0
        cleaned_windows = []

        for win in windows_data:
            tabs: List[str] = win.get("Tabs", []) or []
            # Nếu PowerShell trả về 1 chuỗi thay vì list khi có 1 tab
            if isinstance(tabs, str):
                tabs = [tabs]

            tab_count = win.get("TabCount", len(tabs))
            total_tabs += tab_count

            window_info: Dict[str, Any] = {
                "window_title": win.get("WindowTitle", "Google Chrome"),
                "tab_count": tab_count,
            }

            if include_tab_titles:
                window_info["tabs"] = tabs

            cleaned_windows.append(window_info)

        return {
            "success": True,
            "total_windows": total_windows,
            "total_tabs": total_tabs,
            "windows": cleaned_windows,
            "message": f"Tìm thấy {total_windows} cửa sổ Chrome với tổng cộng {total_tabs} tab đang mở.",
        }

    except json.JSONDecodeError:
        return {
            "success": False,
            "error": "Dữ liệu trả về từ trình duyệt không hợp lệ.",
            "total_windows": 0,
            "total_tabs": 0,
            "windows": [],
        }
    except Exception as e:
        return {
            "success": False,
            "error": f"Lỗi trong quá trình kiểm tra tab Chrome: {str(e)}",
            "total_windows": 0,
            "total_tabs": 0,
            "windows": [],
        }
