# Auto-synthesised skill: auto_get_hanoi_weather
# Generated by VN-MateAI MetaArchitect.
# Yêu cầu gốc: Lấy dữ liệu thời tiết thực tế tại Hà Nội từ API miễn phí như Open-Meteo hoặc wttr.in, trả về nhiệt độ hiện tại, độ ẩm và tình trạng thời tiết

"""
Module lấy dữ liệu thời tiết thực tế tại Hà Nội từ API miễn phí Open-Meteo.
"""

import urllib.request
import json
from typing import Dict, Any, Optional
from core.plugin_manager import export_skill


# Bảng mã WMO Weather interpretation codes -> mô tả tiếng Việt
WMO_WEATHER_CODES: Dict[int, str] = {
    0: "Trời quang đãng",
    1: "Chủ yếu quang đãng",
    2: "Có mây rải rác",
    3: "Nhiều mây / u ám",
    45: "Sương mù",
    48: "Sương mù đọng băng",
    51: "Mưa phùn nhẹ",
    53: "Mưa phùn vừa",
    55: "Mưa phùn dày đặc",
    56: "Mưa phùn đóng băng nhẹ",
    57: "Mưa phùn đóng băng dày đặc",
    61: "Mưa nhỏ",
    63: "Mưa vừa",
    65: "Mưa to",
    66: "Mưa đóng băng nhẹ",
    67: "Mưa đóng băng nặng",
    71: "Tuyết rơi nhẹ",
    73: "Tuyết rơi vừa",
    75: "Tuyết rơi dày",
    77: "Hạt tuyết",
    80: "Mưa rào nhẹ",
    81: "Mưa rào vừa",
    82: "Mưa rào nặng",
    85: "Mưa tuyết nhẹ",
    86: "Mưa tuyết nặng",
    95: "Giông bão",
    96: "Giông bão kèm mưa đá nhẹ",
    99: "Giông bão kèm mưa đá nặng",
}


def _interpret_weather_code(code: int) -> str:
    """Chuyển mã thời tiết WMO sang mô tả tiếng Việt."""
    return WMO_WEATHER_CODES.get(code, f"Không xác định (mã {code})")


def _fetch_json(url: str, timeout: int = 15) -> Dict[str, Any]:
    """Gửi GET request và parse JSON response."""
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) PythonWeatherBot/1.0"}
    )
    with urllib.request.urlopen(req, timeout=timeout) as response:
        data = response.read().decode("utf-8")
        return json.loads(data)


@export_skill(
    name="auto_get_hanoi_weather",
    description=(
        'Lấy dữ liệu thời tiết thực tế tại Hà Nội (nhiệt độ hiện tại, độ ẩm, tình trạng thời tiết) từ API miễn phí Open-Meteo. Trả về kết quả bằng tiếng Việt.\nCác cách người dùng hay nói:\n- "Thời tiết Hà Nội hôm nay thế nào?"\n- "Nhiệt độ ở Hà Nội bây giờ bao nhiêu?"\n- "Cho tôi biết thời tiết hiện tại tại Hà Nội"\n- "Hà Nội hôm nay có mưa không?"\n- "Xem dự báo thời tiết Hà Nội"\nKeywords: weather Hanoi, temperature Hanoi, Hanoi forecast, current weather, thời tiết, nhiệt độ, độ ẩm Ví dụ yêu cầu: «Lấy dữ liệu thời tiết thực tế tại Hà Nội từ API miễn phí như Open-Meteo hoặc wttr.in, trả về nhiệt độ hiện tại, độ ẩm và tình trạng thời tiết».'
    ),
    parameters_schema={
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": False,
    }
)
def auto_get_hanoi_weather() -> Dict[str, Any]:
    """
    Lấy thời tiết thực tế tại Hà Nội từ Open-Meteo API.

    Returns:
        Dict chứa nhiệt độ, độ ẩm, tình trạng thời tiết và thông tin bổ sung.
    """
    # Tọa độ Hà Nội
    latitude: float = 21.0285
    longitude: float = 105.8542

    url: str = (
        f"https://api.open-meteo.com/v1/forecast?"
        f"latitude={latitude}&longitude={longitude}"
        f"&current=temperature_2m,relative_humidity_2m,apparent_temperature,"
        f"weather_code,wind_speed_10m,wind_direction_10m,pressure_msl"
        f"&timezone=Asia%2FBangkok"
    )

    try:
        data: Dict[str, Any] = _fetch_json(url)
    except Exception as e:
        # Fallback: thử wttr.in nếu Open-Meteo thất bại
        try:
            return _fallback_wttr_in()
        except Exception as fallback_err:
            return {
                "success": False,
                "error": f"Không thể lấy dữ liệu thời tiết. Open-Meteo: {str(e)}. wttr.in: {str(fallback_err)}",
                "location": "Hà Nội",
            }

    try:
        current: Dict[str, Any] = data.get("current", {})
        current_units: Dict[str, str] = data.get("current_units", {})

        temperature: Optional[float] = current.get("temperature_2m")
        humidity: Optional[int] = current.get("relative_humidity_2m")
        weather_code: Optional[int] = current.get("weather_code")
        apparent_temp: Optional[float] = current.get("apparent_temperature")
        wind_speed: Optional[float] = current.get("wind_speed_10m")
        wind_direction: Optional[int] = current.get("wind_direction_10m")
        pressure: Optional[float] = current.get("pressure_msl")
        observation_time: Optional[str] = current.get("time")

        weather_description: str = _interpret_weather_code(weather_code) if weather_code is not None else "Không xác định"

        temp_unit: str = current_units.get("temperature_2m", "°C")
        humidity_unit: str = current_units.get("relative_humidity_2m", "%")
        wind_unit: str = current_units.get("wind_speed_10m", "km/h")
        pressure_unit: str = current_units.get("pressure_msl", "hPa")

        # Tạo summary dễ đọc
        summary_parts = [f"🌍 Thời tiết Hà Nội hiện tại:"]
        if temperature is not None:
            summary_parts.append(f"🌡️ Nhiệt độ: {temperature}{temp_unit}")
        if apparent_temp is not None:
            summary_parts.append(f"🤔 Cảm giác như: {apparent_temp}{temp_unit}")
        if humidity is not None:
            summary_parts.append(f"💧 Độ ẩm: {humidity}{humidity_unit}")
        summary_parts.append(f"☁️ Tình trạng: {weather_description}")
        if wind_speed is not None:
            summary_parts.append(f"💨 Gió: {wind_speed} {wind_unit}")
        if pressure is not None:
            summary_parts.append(f"🔵 Áp suất: {pressure} {pressure_unit}")
        if observation_time:
            summary_parts.append(f"🕐 Thời điểm quan trắc: {observation_time}")

        summary: str = "\n".join(summary_parts)

        return {
            "success": True,
            "location": "Hà Nội, Việt Nam",
            "latitude": latitude,
            "longitude": longitude,
            "temperature": temperature,
            "temperature_unit": temp_unit,
            "apparent_temperature": apparent_temp,
            "humidity": humidity,
            "humidity_unit": humidity_unit,
            "weather_condition": weather_description,
            "weather_code": weather_code,
            "wind_speed": wind_speed,
            "wind_speed_unit": wind_unit,
            "wind_direction": wind_direction,
            "pressure": pressure,
            "pressure_unit": pressure_unit,
            "observation_time": observation_time,
            "summary": summary,
            "source": "Open-Meteo API",
        }

    except Exception as e:
        return {
            "success": False,
            "error": f"Lỗi khi phân tích dữ liệu thời tiết: {str(e)}",
            "location": "Hà Nội",
            "raw_data": data,
        }


def _fallback_wttr_in() -> Dict[str, Any]:
    """
    Fallback: lấy thời tiết từ wttr.in khi Open-Meteo không khả dụng.
    """
    url: str = "https://wttr.in/Hanoi?format=j1"
    data: Dict[str, Any] = _fetch_json(url, timeout=10)

    current_condition = data.get("current_condition", [{}])[0]

    temperature_c: str = current_condition.get("temp_C", "N/A")
    humidity: str = current_condition.get("humidity", "N/A")
    feels_like: str = current_condition.get("FeelsLikeC", "N/A")
    weather_desc_list = current_condition.get("lang_vi", current_condition.get("weatherDesc", [{}]))

    if isinstance(weather_desc_list, list) and len(weather_desc_list) > 0:
        weather_desc: str = weather_desc_list[0].get("value", "Không xác định")
    else:
        weather_desc = "Không xác định"

    wind_speed_kmph: str = current_condition.get("windspeedKmph", "N/A")
    pressure: str = current_condition.get("pressure", "N/A")
    observation_time: str = current_condition.get("observation_time", "N/A")

    summary_parts = [
        f"🌍 Thời tiết Hà Nội hiện tại:",
        f"🌡️ Nhiệt độ: {temperature_c}°C",
        f"🤔 Cảm giác như: {feels_like}°C",
        f"💧 Độ ẩm: {humidity}%",
        f"☁️ Tình trạng: {weather_desc}",
        f"💨 Gió: {wind_speed_kmph} km/h",
        f"🔵 Áp suất: {pressure} hPa",
        f"🕐 Thời điểm quan trắc: {observation_time}",
    ]
    summary: str = "\n".join(summary_parts)

    temp_val: Optional[float] = None
    try:
        temp_val = float(temperature_c)
    except (ValueError, TypeError):
        pass

    humidity_val: Optional[int] = None
    try:
        humidity_val = int(humidity)
    except (ValueError, TypeError):
        pass

    return {
        "success": True,
        "location": "Hà Nội, Việt Nam",
        "temperature": temp_val,
        "temperature_unit": "°C",
        "apparent_temperature": feels_like,
        "humidity": humidity_val,
        "humidity_unit": "%",
        "weather_condition": weather_desc,
        "wind_speed": wind_speed_kmph,
        "wind_speed_unit": "km/h",
        "pressure": pressure,
        "pressure_unit": "hPa",
        "observation_time": observation_time,
        "summary": summary,
        "source": "wttr.in (fallback)",
    }
