"""
Auto-synthesised skill: auto_play_music
Generated by VN-MateAI MetaArchitect.
"""

import webbrowser
import urllib.parse
import urllib.request
import re
import json
from typing import Any, Dict, Optional
from core.plugin_manager import export_skill


def _search_youtube(query: str) -> Optional[Dict[str, str]]:
    """Search YouTube and extract the first video ID and title."""
    try:
        encoded_query = urllib.parse.quote_plus(query)
        search_url = f"https://www.youtube.com/results?search_query={encoded_query}"
        
        req = urllib.request.Request(
            search_url,
            headers={
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                "Accept-Language": "en-US,en;q=0.9",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            }
        )
        
        with urllib.request.urlopen(req, timeout=15) as response:
            html_content = response.read().decode("utf-8", errors="replace")
        
        video_id = None
        video_title = None
        
        # Method 1: Parse ytInitialData JSON from the page
        yt_data_match = re.search(r"var\s+ytInitialData\s*=\s*(\{.*?\});\s*</script>", html_content, re.DOTALL)
        if not yt_data_match:
            yt_data_match = re.search(r"ytInitialData\s*=\s*(\{.*?\});\s*", html_content, re.DOTALL)
        
        if yt_data_match:
            try:
                yt_data = json.loads(yt_data_match.group(1))
                contents = (
                    yt_data.get("contents", {})
                    .get("twoColumnSearchResultsRenderer", {})
                    .get("primaryContents", {})
                    .get("sectionListRenderer", {})
                    .get("contents", [])
                )
                
                for section in contents:
                    items = (
                        section.get("itemSectionRenderer", {})
                        .get("contents", [])
                    )
                    for item in items:
                        video_renderer = item.get("videoRenderer")
                        if video_renderer:
                            vid = video_renderer.get("videoId")
                            title_runs = video_renderer.get("title", {}).get("runs", [])
                            if vid and title_runs:
                                video_id = vid
                                video_title = title_runs[0].get("text", "Unknown Title")
                                break
                    if video_id:
                        break
            except (json.JSONDecodeError, KeyError, IndexError, TypeError):
                pass
        
        # Method 2: Regex fallback for video ID from HTML
        if not video_id:
            patterns = [
                r'"videoId"\s*:\s*"([a-zA-Z0-9_-]{11})"',
                r'/watch\?v=([a-zA-Z0-9_-]{11})',
                r'"url"\s*:\s*"/watch\?v=([a-zA-Z0-9_-]{11})',
            ]
            for pattern in patterns:
                match = re.search(pattern, html_content)
                if match:
                    video_id = match.group(1)
                    break
        
        # Try to extract title if we have video_id but no title
        if video_id and not video_title:
            title_pattern = rf'"videoId"\s*:\s*"{re.escape(video_id)}".*?"title"\s*:\s*\{{"runs"\s*:\s*\[\{{"text"\s*:\s*"(.*?)"\}}'
            title_match = re.search(title_pattern, html_content)
            if title_match:
                video_title = title_match.group(1)
            else:
                # Fallback: fetch the video page to get the title
                try:
                    video_page_url = f"https://www.youtube.com/watch?v={video_id}"
                    req2 = urllib.request.Request(
                        video_page_url,
                        headers={
                            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                        }
                    )
                    with urllib.request.urlopen(req2, timeout=10) as resp2:
                        video_html = resp2.read().decode("utf-8", errors="replace")
                    
                    og_title = re.search(r'<meta\s+property="og:title"\s+content="([^"]+)"', video_html)
                    if og_title:
                        video_title = og_title.group(1)
                    else:
                        t_match = re.search(r"<title>(.*?)(?:\s*-\s*YouTube)?\s*</title>", video_html)
                        if t_match:
                            video_title = t_match.group(1).strip()
                except Exception:
                    video_title = query
        
        if video_id:
            return {
                "video_id": video_id,
                "title": video_title or query,
            }
        
        return None
        
    except urllib.error.HTTPError as e:
        raise RuntimeError(f"HTTP error while searching YouTube: {e.code} {e.reason}")
    except urllib.error.URLError as e:
        raise RuntimeError(f"Network error while searching YouTube: {e.reason}")
    except Exception as e:
        raise RuntimeError(f"Unexpected error during YouTube search: {str(e)}")


def _open_in_browser(url: str) -> bool:
    """Open a URL in the default web browser."""
    try:
        return webbrowser.open(url)
    except Exception:
        return False


@export_skill(
    name="auto_play_music",
    description=(
        'Automatically search for a song/music video on YouTube by keyword, find the first matching video, and immediately start playback in the default web browser with autoplay enabled. Returns the song title and URL. Ví dụ yêu cầu: «mở bài hát …, bật nhạc …, phát nhạc / nghe nhạc trên YouTube».'
    ),
    parameters_schema={
        "type": "object",
        "properties": {
            "song_name": {
                "type": "string",
                "description": "The name of the song, artist, or search keyword to find and play on YouTube."
            }
        },
        "required": ["song_name"]
    }
)
def auto_play_music(song_name: str) -> Dict[str, Any]:
    """
    Search YouTube for a song and automatically play it in the browser.
    
    Args:
        song_name: The song name, artist name, or any search query for YouTube.
        
    Returns:
        Dictionary with status, song title, video URL, and video ID.
    """
    if not song_name or not song_name.strip():
        return {
            "success": False,
            "error": "song_name cannot be empty. Please provide a song name or search keyword.",
            "song_name": song_name,
            "title": None,
            "url": None,
            "video_id": None,
        }
    
    search_query = song_name.strip()
    
    # Add "music" or "official" hints if the query seems like just a song name
    # to improve search relevance
    enhanced_query = search_query
    lower_query = search_query.lower()
    music_keywords = ["music", "official", "audio", "lyric", "mv", "song", "nhạc", "bài hát"]
    if not any(kw in lower_query for kw in music_keywords):
        enhanced_query = f"{search_query} official audio"
    
    try:
        # Try enhanced query first
        result = _search_youtube(enhanced_query)
        
        # Fallback to original query if enhanced didn't work
        if not result and enhanced_query != search_query:
            result = _search_youtube(search_query)
        
        if not result:
            return {
                "success": False,
                "error": f"No video found on YouTube for: '{search_query}'. Please try a different search term.",
                "song_name": search_query,
                "title": None,
                "url": None,
                "video_id": None,
            }
        
        video_id = result["video_id"]
        video_title = result["title"]
        
        # Build autoplay URL
        watch_url = f"https://www.youtube.com/watch?v={video_id}&autoplay=1"
        
        # Open in browser with autoplay
        browser_opened = _open_in_browser(watch_url)
        
        if not browser_opened:
            # Fallback: try without autoplay parameter
            fallback_url = f"https://www.youtube.com/watch?v={video_id}"
            browser_opened = _open_in_browser(fallback_url)
            
            if not browser_opened:
                return {
                    "success": False,
                    "error": (
                        f"Found video '{video_title}' but failed to open browser. "
                        f"You can manually open: {watch_url}"
                    ),
                    "song_name": search_query,
                    "title": video_title,
                    "url": watch_url,
                    "video_id": video_id,
                }
        
        return {
            "success": True,
            "message": f"Now playing: {video_title}",
            "song_name": search_query,
            "title": video_title,
            "url": watch_url,
            "video_id": video_id,
        }
        
    except RuntimeError as e:
        return {
            "success": False,
            "error": str(e),
            "song_name": search_query,
            "title": None,
            "url": None,
            "video_id": None,
        }
    except Exception as e:
        return {
            "success": False,
            "error": f"An unexpected error occurred: {str(e)}",
            "song_name": search_query,
            "title": None,
            "url": None,
            "video_id": None,
        }