# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Dương Thanh Lịch — VN-MateAI. See LICENSE and NOTICE.
"""
mateai/application/devfleet/provider.py
=======================================
Ranh giới giữa VN-MateAI và Dev Fleet (prompt §6): Project Manager / Scheduler / Service KHÔNG tự gọi HTTP, SSH, Ansible
hay CLI OpenClaw — chỉ gọi qua `DevFleetProvider`. Bản cài đặt thật nằm ở tầng hạ tầng
(`infrastructure/connectors/dev_fleet_master.py`) và chỉ nói chuyện với Ubuntu Master, KHÔNG với từng Mac.

Mọi phương thức trả dữ liệu thô (dict) theo hợp đồng Master API; chuẩn hoá nằm ở `models.py`.
"""
from __future__ import annotations

from typing import Any, Dict, List, Protocol


class FleetError(Exception):
    """Lỗi từ phía Master / đường truyền. `kind`: unavailable | not_found | rejected | incompatible | bad_response."""

    def __init__(self, message: str, kind: str = "unavailable") -> None:
        super().__init__(message)
        self.kind = kind


class DevFleetProvider(Protocol):
    async def health(self) -> Dict[str, Any]: ...
    async def list_workers(self) -> List[Dict[str, Any]]: ...
    async def get_worker(self, worker_id: str) -> Dict[str, Any]: ...
    async def list_agents(self) -> List[Dict[str, Any]]: ...
    async def get_metrics(self, worker_id: str) -> Dict[str, Any]: ...
    async def get_git_status(self, worker_id: str, repository: str) -> Dict[str, Any]: ...
    async def dispatch_task(self, spec: Dict[str, Any], *, worker_id: str, idempotency_key: str) -> Dict[str, Any]: ...
    async def get_task_status(self, master_task_id: str) -> Dict[str, Any]: ...
    async def get_task_logs(self, master_task_id: str, tail: int = 200) -> Dict[str, Any]: ...
    async def cancel_task(self, master_task_id: str, *, idempotency_key: str) -> Dict[str, Any]: ...
    async def pause_task(self, master_task_id: str, *, idempotency_key: str) -> Dict[str, Any]: ...
    async def resume_task(self, master_task_id: str, *, idempotency_key: str) -> Dict[str, Any]: ...
